"""Views split by domain -- urls.py only ever does `from . import views`
then `views.<name>`, so this package re-exports every URL-routable view
under the same `organizer.views` name it always had. Private helpers
(leading underscore) stay local to whichever module builds them; only
public views need to be listed here.
"""

from .dashboard import (
    activity_ping,
    browse_folders,
    command_palette_search,
    dashboard,
    desktop_shell_enter,
    makerere_wizard,
    owner_console,
    owner_mode_toggle,
    owner_setup,
    profile_activate,
    profile_delete,
    profile_edit,
    profile_wizard,
    privacy_policy,
    profiles_list,
    pulse_data,
    settings_edit,
    setup_item_dismiss,
    setup_items_restore,
    sorting_report,
    start,
    status_bar_data,
)
from .files import (
    category_test,
    export_bundles,
    export_delete,
    export_download,
    folder_rules,
    folder_sort_cancel,
    folder_sort_start,
    import_plans,
    inbox_approve,
    inbox_clear_all,
    inbox_ignore,
    inbox_reroute,
    move_clear_history,
    move_clear_one,
    move_history,
    move_history_compact,
    move_relocate,
    move_summarize,
    move_summary_pdf,
    move_summary_view,
    move_undo,
    organization_dna,
    organization_memory,
    organization_memory_rule_delete,
    organization_memory_rule_update,
    preview_scan,
    rule_test,
    sorting_inbox,
    undo_recent,
)
from .study import (
    assignment_tracker,
    assignment_tracker_archive_missed,
    assignment_tracker_item_delete,
    assignment_tracker_item_update,
    course_guide_generate,
    course_guide_pdf,
    course_guide_view,
    digest_detail,
    digest_overview,
    exam_countdown,
    first_run_checklist,
    flashcard_delete,
    flashcard_grade,
    flashcards,
    grade_target_delete,
    grade_target_planner,
    learning_route,
    learning_routes,
    muele_connection,
    notification_clear,
    notifications_view,
    open_watched_folder,
    past_paper_analysis,
    resource_radar,
    review_mark_done,
    review_queue,
    review_skip,
    study_home,
    study_timetable,
    subject_dashboard,
    subject_memory_detail,
    support_message,
    timeline_view,
    war_room,
    weakness_radar,
)
from .career import (
    career_digest_generate,
    career_digest_view,
    career_home,
    career_profile_update,
    content_draft_approve,
    content_draft_delete,
    content_draft_detail,
    content_draft_export_html,
    content_draft_export_markdown,
    content_draft_mark_posted,
    content_draft_polish,
    content_draft_publish,
    content_drafts,
    content_drafts_delete_posted,
    project_delete,
    project_detail,
    project_generate_draft,
    project_studio,
    publishing_channel_delete,
    publishing_channels,
)
from .integrations import (
    connections_home,
    drive_callback,
    drive_backup_retry,
    drive_connect,
    drive_disconnect,
    muele_connect,
    muele_courses,
    muele_sync_status,
    timetable_colleges,
    timetable_connect,
    task_status,
    timetable_document_delete,
    timetable_document_download,
    timetable_document_upload,
    timetable_entry_create,
    timetable_entry_delete,
    timetable_groups,
    timetable_semesters,
    timetable_sync_now,
    timetable_view,
)

__all__ = [
    "activity_ping", "assignment_tracker", "assignment_tracker_archive_missed", "assignment_tracker_item_delete",
    "assignment_tracker_item_update", "browse_folders", "career_digest_generate",
    "career_digest_view", "career_home", "career_profile_update", "category_test",
    "command_palette_search",
    "content_draft_approve", "content_draft_delete", "content_draft_detail",
    "content_draft_export_html", "content_draft_export_markdown",
    "content_draft_mark_posted", "content_draft_polish", "content_draft_publish",
    "content_drafts", "content_drafts_delete_posted", "course_guide_generate", "course_guide_pdf", "course_guide_view",
    "connections_home", "dashboard", "desktop_shell_enter", "digest_detail", "digest_overview",
    "drive_backup_retry", "drive_callback", "drive_connect", "drive_disconnect", "exam_countdown", "export_bundles", "export_delete",
    "export_download", "first_run_checklist", "flashcard_delete", "flashcard_grade",
    "flashcards", "folder_rules", "folder_sort_cancel", "folder_sort_start",
    "grade_target_delete", "grade_target_planner",
    "import_plans", "inbox_approve", "inbox_clear_all", "inbox_ignore", "inbox_reroute", "learning_route",
    "learning_routes", "makerere_wizard", "move_clear_history", "move_clear_one", "move_history",
    "move_history_compact", "move_relocate", "move_summarize",
    "move_summary_pdf", "move_summary_view", "move_undo", "muele_connect",
    "muele_connection", "muele_courses", "muele_sync_status", "notification_clear", "notifications_view",
    "open_watched_folder",
    "organization_dna", "organization_memory", "organization_memory_rule_delete",
    "organization_memory_rule_update", "owner_console", "owner_mode_toggle",
    "owner_setup", "past_paper_analysis", "preview_scan", "privacy_policy", "profile_activate",
    "profile_delete", "profile_edit", "profile_wizard", "profiles_list",
    "project_delete", "project_detail", "project_generate_draft", "project_studio", "pulse_data",
    "publishing_channel_delete", "publishing_channels", "resource_radar",
    "review_mark_done", "review_queue", "review_skip", "rule_test", "settings_edit",
    "setup_item_dismiss", "setup_items_restore",
    "sorting_inbox", "sorting_report", "start", "status_bar_data", "study_home", "study_timetable", "subject_dashboard",
    "subject_memory_detail", "support_message", "task_status", "timeline_view", "timetable_colleges",
    "timetable_connect", "timetable_document_delete", "timetable_document_download",
    "timetable_document_upload", "timetable_entry_create", "timetable_entry_delete",
    "timetable_groups", "timetable_semesters",
    "timetable_sync_now", "timetable_view", "undo_recent", "war_room",
    "weakness_radar",
]
